import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--data-path', required=True, type=str, help="Path to binarized_mnist.npz")
parser.add_argument('--N', type=int, default=784, help="The number of pixels.")
parser.add_argument('--epoch', type=int, default=100, help="How many epoches of training")
parser.add_argument('--Dmax', type=int, default=10, help="Bond dimension of the MPS")
parser.add_argument('--device', type=str, default='cuda:0',help="gpu")
parser.add_argument('--batch_size', type=int, default=50000,help="Batch size of each step.")
parser.add_argument('--seed', type=int, default=42,help="Random seed.")
parser.add_argument('--con', type=int, default=30,help="The number of pixels considered.")
parser.add_argument('--fixed_bias', type=int, default=1)
parser.add_argument('--lr', type=float, default=1e-4, help="Learning rate of the training.")
parser.add_argument('--weightDec', type=float, default=1e-4)
parser.add_argument('--clip_grad', type=int, default=1)
parser.add_argument('--max_norm', type=float, default=1)
parser.add_argument('--init', type=float,  default=1e-9)
parser.add_argument('--net_depth', type=int,  default=8)
parser.add_argument('--sample', type=int,  default=0)
parser.add_argument('--lr_scheduler', type=int,  default=100)

args = parser.parse_args()
